apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
  namespace: hello-flask
spec:
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8000
  type: LoadBalancer
