apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  namespace: hello-flask
  labels:
    app: hello-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-flask 
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: cardene/hello-flask:1.0
        ports:
        - containerPort: 8000
